apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
  labels:
    chapter: secrets
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: tkb-secret
  containers:
    - name: pod-secret
      image: nginx
      volumeMounts:
        - mountPath: /etc/tkb
          name: secret-vol
